import { Field, FieldBool, FieldInt, FieldReal, FieldString, FieldUnreal } from "../Field"

export interface FieldUnit<T extends Field.ValueType> extends Field<T> {}
export class FieldUnitBool extends FieldBool implements FieldUnit<boolean> {}
export class FieldUnitInt extends FieldInt implements FieldUnit<number> {}
export class FieldUnitReal extends FieldReal implements FieldUnit<number> {}
export class FieldUnitUnreal extends FieldUnreal implements FieldUnit<number> {}
export class FieldUnitString extends FieldString implements FieldUnit<string> {}

export namespace FieldUnitList {
    export let AllowCustomTeamColor = new FieldUnitBool("utcc")
    export let Attack1ProjectileHomingEnabled = new FieldUnitBool("umh1")
    export let Attack1ShowUI = new FieldUnitBool("uwu1")
    export let Attack2ProjectileHomingEnabled = new FieldUnitBool("umh2")
    export let Attack2ShowUI = new FieldUnitBool("uwu2")
    export let CanDropItemsOnDeath = new FieldUnitBool("udro")
    export let CanFlee = new FieldUnitBool("ufle")
    export let CategorizationCampaign = new FieldUnitBool("ucam")
    export let CategorizationSpecial = new FieldUnitBool("uspe")
    export let DisplayasNeutralHostile = new FieldUnitBool("uhos")
    export let HasTilesetSpecificData = new FieldUnitBool("utss")
    export let HasWaterShadow = new FieldUnitBool("ushr")
    export let HideMinimapDisplay = new FieldUnitBool("uhom")
    export let IsaBuilding = new FieldUnitBool("ubdg")
    export let PlaceableInEditor = new FieldUnitBool("uine")
    export let ScaleProjectiles = new FieldUnitBool("uscb")
    export let SelectionCircleOnWater = new FieldUnitBool("usew")
    export let Sleeps = new FieldUnitBool("usle")
    export let UseClickHelper = new FieldUnitBool("uuch")
    export let UseExtendedLineofSight = new FieldUnitBool("ulos")
    export let Hero_GroupSeparationEnabled = new FieldUnitBool("urpo")
    export let Hero_HideHeroDeathMsg = new FieldUnitBool("uhhd")
    export let Hero_HideHeroInterfaceIcon = new FieldUnitBool("uhhb")
    export let Hero_HideHeroMinimapDisplay = new FieldUnitBool("uhhm")
    export let NeutralBuildingShowsMinimapIcon = new FieldUnitBool("unbm")
    export let NeutralBuildingValidAsRandomBuilding = new FieldUnitBool("unbr")
    export let RevivesDeadHeros = new FieldUnitBool("urev")

    export let Attack1AreaofEffectFullDamage = new FieldUnitInt("ua1f")
    export let Attack1AreaofEffectMediumDamage = new FieldUnitInt("ua1h")
    export let Attack1AreaofEffectSmallDamage = new FieldUnitInt("ua1q")
    export let Attack1DamageBase = new FieldUnitInt("ua1b")
    export let Attack1DamageSidesperDie = new FieldUnitInt("ua1s")
    export let Attack1DamageUpgradeAmount = new FieldUnitInt("udu1")
    export let Attack1DamageDice = new FieldUnitInt("ua1d")
    export let Attack1MaximumTargets = new FieldUnitInt("utc1")
    export let Attack1ProjectileSpeed = new FieldUnitInt("ua1z")
    export let Attack1Range = new FieldUnitInt("ua1r")
    export let Attack2AreaofEffectFullDamage = new FieldUnitInt("ua2f")
    export let Attack2AreaofEffectMediumDamage = new FieldUnitInt("ua2h")
    export let Attack2AreaofEffectSmallDamage = new FieldUnitInt("ua2q")
    export let Attack2DamageBase = new FieldUnitInt("ua2b")
    export let Attack2DamageSidesperDie = new FieldUnitInt("ua2s")
    export let Attack2DamageUpgradeAmount = new FieldUnitInt("udu2")
    export let Attack2DamagebooleanofDice = new FieldUnitInt("ua2d")
    export let Attack2MaximumbooleanofTargets = new FieldUnitInt("utc2")
    export let Attack2ProjectileSpeed = new FieldUnitInt("ua2z")
    export let Attack2Range = new FieldUnitInt("ua2r")
    export let AttacksEnabled = new FieldUnitInt("uaen")
    export let BuildTime = new FieldUnitInt("ubld")
    export let ButtonPositionX = new FieldUnitInt("ubpx")
    export let ButtonPositionY = new FieldUnitInt("ubpy")
    export let DeathType = new FieldUnitInt("udea")
    export let DefenseBase = new FieldUnitInt("udef")
    export let DefenseUpgradeBonus = new FieldUnitInt("udup")
    export let ElevationSamplePoints = new FieldUnitInt("uept")
    export let FoodCost = new FieldUnitInt("ufoo")
    export let FoodProduced = new FieldUnitInt("ufma")
    export let GoldBountyAwardedBase = new FieldUnitInt("ubba")
    export let GoldBountyAwardedSidesperDie = new FieldUnitInt("ubsi")
    export let GoldBountyAwardedbooleanofDice = new FieldUnitInt("ubdi")
    export let GoldCost = new FieldUnitInt("ugol")
    export let HitPointsMaximumBase = new FieldUnitInt("uhpm")
    export let LumberBountyAwardedBase = new FieldUnitInt("ulba")
    export let LumberBountyAwardedSidesperDie = new FieldUnitInt("ulbs")
    export let LumberBountyAwardedbooleanofDice = new FieldUnitInt("ulbd")
    export let LumberCost = new FieldUnitInt("ulum")
    export let ManaInitialAmount = new FieldUnitInt("umpi")
    export let ManaMaximum = new FieldUnitInt("umpm")
    export let MinimumAttackRange = new FieldUnitInt("uamn")
    export let OrientationInterpolation = new FieldUnitInt("uori")
    export let PointValue = new FieldUnitInt("upoi")
    export let Priority = new FieldUnitInt("upri")
    export let RepairGoldCost = new FieldUnitInt("ugor")
    export let RepairLumberCost = new FieldUnitInt("ulur")
    export let RepairTime = new FieldUnitInt("urtm")
    export let SightRadiusDay = new FieldUnitInt("usid")
    export let SightRadiusNight = new FieldUnitInt("usin")
    export let SoundLoopingFadeInRate = new FieldUnitInt("ulfi")
    export let SoundLoopingFadeOutRate = new FieldUnitInt("ulfo")
    export let MovementSpeedBase = new FieldUnitInt("umvs")
    export let MovementSpeedMaximum = new FieldUnitInt("umas")
    export let MovementSpeedMinimum = new FieldUnitInt("umis")
    export let StockMaximum = new FieldUnitInt("usma")
    export let StockReplenishInterval = new FieldUnitInt("usrg")
    export let StockStartDelay = new FieldUnitInt("usst")
    export let TeamColor = new FieldUnitInt("utco")
    export let TintingColorBlue = new FieldUnitInt("uclb")
    export let TintingColorGreen = new FieldUnitInt("uclg")
    export let TintingColorRed = new FieldUnitInt("uclr")
    export let Hero_FormationRank = new FieldUnitInt("ufor")
    export let Hero_GroupSeparationGroupNumber = new FieldUnitInt("urpg")
    export let Hero_GroupSeparationParameter = new FieldUnitInt("urpp")
    export let Hero_GroupSeparationPriority = new FieldUnitInt("urpr")
    export let Hero_Level = new FieldUnitInt("ulev")
    export let Hero_ProperNamesUsed = new FieldUnitInt("upru")
    export let Hero_StartingAgility = new FieldUnitInt("uagi")
    export let Hero_StartingIntelligence = new FieldUnitInt("uint")
    export let Hero_StartingStrength = new FieldUnitInt("ustr")
    export let Hero_TransportedSize = new FieldUnitInt("ucar")

    export let ShadowImageWidth = new FieldUnitReal("ushw")
    export let ShadowImageHeight = new FieldUnitReal("ushh")
    export let ShadowImageCenterY = new FieldUnitReal("ushy")
    export let ShadowImageCenterX = new FieldUnitReal("ushx")
    export let SelectionScale = new FieldUnitReal("ussc")
    export let SelectionCircleHeight = new FieldUnitReal("uslz")
    export let ScalingValue = new FieldUnitReal("usca")
    export let MaximumRollAngledegrees = new FieldUnitReal("umxr")
    export let MaximumPitchAngledegrees = new FieldUnitReal("umxp")
    export let FogOfWarSampleRadius = new FieldUnitReal("ufrd")
    export let ElevationSampleRadius = new FieldUnitReal("uerd")
    export let AnimationWalkSpeed = new FieldUnitReal("uwal")
    export let AnimationRunSpeed = new FieldUnitReal("urun")
    export let AnimationBlendTimeseconds = new FieldUnitReal("uble")
    
    export let TurnRate = new FieldUnitUnreal("umvr")
    export let PropulsionWindowdegrees = new FieldUnitUnreal("uprw")
    export let ProjectileLaunchZSwimming = new FieldUnitUnreal("ulsz")
    export let ProjectileLaunchZ = new FieldUnitUnreal("ulpz")
    export let ProjectileLaunchY = new FieldUnitUnreal("ulpy")
    export let ProjectileLaunchX = new FieldUnitUnreal("ulpx")
    export let ProjectileImpactZSwimming = new FieldUnitUnreal("uisz")
    export let ProjectileImpactZ = new FieldUnitUnreal("uimz")
    export let OccluderHeight = new FieldUnitUnreal("uocc")
    export let ManaRegeneration = new FieldUnitUnreal("umpr")
    export let HitPointsRegenerationRate = new FieldUnitUnreal("uhpr")
    export let MovementHeightMinimum = new FieldUnitUnreal("umvf")
    export let MovementHeight = new FieldUnitUnreal("umvh")
    export let DeathTimeseconds = new FieldUnitUnreal("udtm")
    export let CollisionSize = new FieldUnitUnreal("ucol")
    export let Attack2RangeMotionBuffer = new FieldUnitUnreal("urb2")
    export let Attack2ProjectileArc = new FieldUnitUnreal("uma2")
    export let Attack2DamageSpillRadius = new FieldUnitUnreal("usr2")
    export let Attack2DamageSpillDistance = new FieldUnitUnreal("usd2")
    export let Attack2DamageLossFactor = new FieldUnitUnreal("udl2")
    export let Attack2DamageFactorSmall = new FieldUnitUnreal("uqd2")
    export let Attack2DamageFactorMedium = new FieldUnitUnreal("uhd2")
    export let Attack2CooldownTime = new FieldUnitUnreal("ua2c")
    export let Attack2AnimationDamagePoint = new FieldUnitUnreal("udp2")
    export let Attack2AnimationBackswingPoint = new FieldUnitUnreal("ubs2")
    export let Attack1RangeMotionBuffer = new FieldUnitUnreal("urb1")
    export let Attack1ProjectileArc = new FieldUnitUnreal("uma1")
    export let Attack1DamageSpillRadius = new FieldUnitUnreal("usr1")
    export let Attack1DamageSpillDistance = new FieldUnitUnreal("usd1")
    export let Attack1DamageLossFactor = new FieldUnitUnreal("udl1")
    export let Attack1DamageFactorSmall = new FieldUnitUnreal("uqd1")
    export let Attack1DamageFactorMedium = new FieldUnitUnreal("uhd1")
    export let Attack1CooldownTime = new FieldUnitUnreal("ua1c")
    export let Attack1AnimationDamagePoint = new FieldUnitUnreal("udp1")
    export let Attack1AnimationBackswingPoint = new FieldUnitUnreal("ubs1")
    export let AnimationCastPoint = new FieldUnitUnreal("ucpt")
    export let AnimationCastBackswing = new FieldUnitUnreal("ucbs")
    export let AIPlacementRadius = new FieldUnitUnreal("uabr")
    export let AcquisitionRange = new FieldUnitUnreal("uacq")
    export let StrengthPerLevel = new FieldUnitUnreal("ustp")
    export let IntelligencePerLevel = new FieldUnitUnreal("uinp")
    export let AgilityPerLevel = new FieldUnitUnreal("uagp")
    export let PlacementRequiresWaterRadius = new FieldUnitUnreal("upaw")
    
    export let AIPlacementType = new FieldUnitString("uabt")
    /** 'Ethereal', 'Flesh', 'Wood', 'Stone', 'Metal' */
    export let ArmorSoundType = new FieldUnitString("uarm")
    /** 'normal', 'small', 'medium', 'large', 'fort', 'hero', 'divine', 'none' */
    export let ArmorType = new FieldUnitString("udty")
    export let ArtSpecial = new FieldUnitString("uspa")
    export let ArtTarget = new FieldUnitString("utaa")
    export let Attack1AreaofEffectTargets = new FieldUnitString("ua1p")
    /** 'unknown', 'normal', 'pierce', 'siege', 'spells', 'chaos', 'magic', 'hero' */
    export let Attack1AttackType = new FieldUnitString("ua1t")
    export let Attack1ProjectileArt = new FieldUnitString("ua1m")
    /** 'air', 'alive', 'allies', 'ancient', 'dead', 'debris', 'decoration', 'enemies', 'friend', 'ground', 'hero',
      * 'invulnerable', 'item', 'mechanical', 'neutral', 'nonancient', 'none', 'nonhero', 'nonsapper', 'notself',
      * 'organic', 'player', 'playerunits', 'sapper', 'self', 'structure', 'terrain', 'tree', 'vulnerable', 'wall', */
    export let Attack1TargetsAllowed = new FieldUnitString("ua1g")
    /** 'Nothing', 'AxeMediumChop', 'MetalHeavyBash', 'MetalHeavyChop',
      * 'MetalHeavySlice', 'MetalLightChop', 'MetalLightSlice', 'MetalMediumBash', 'MetalMediumChop',
      * 'MetalMediumSlice', 'RockHeavyBash', 'WoodHeavyBash', 'WoodLightBash', 'WoodMediumBash' */
    export let Attack1WeaponSound = new FieldUnitString("ucs1")
    /** 'normal', 'instant', 'artillery', 'aline', 'missile', 'splash', 'bounce', 'line' */
    export let Attack1WeaponType = new FieldUnitString("ua1w")
    export let Attack2AreaofEffectTargets = new FieldUnitString("ua2p")
    /** 'unknown', 'normal', 'pierce', 'siege', 'spells', 'chaos', 'magic', 'hero' */
    export let Attack2AttackType = new FieldUnitString("ua2t")
    export let Attack2ProjectileArt = new FieldUnitString("ua2m")
    /** 'air', 'alive', 'allies', 'ancient', 'dead', 'debris', 'decoration', 'enemies', 'friend', 'ground', 'hero',
      * 'invulnerable', 'item', 'mechanical', 'neutral', 'nonancient', 'none', 'nonhero', 'nonsapper', 'notself',
      * 'organic', 'player', 'playerunits', 'sapper', 'self', 'structure', 'terrain', 'tree', 'vulnerable', 'wall', */
    export let Attack2TargetsAllowed = new FieldUnitString("ua2g")
    /** 'Nothing', 'AxeMediumChop', 'MetalHeavyBash', 'MetalHeavyChop',
      * 'MetalHeavySlice', 'MetalLightChop', 'MetalLightSlice', 'MetalMediumBash', 'MetalMediumChop',
      * 'MetalMediumSlice', 'RockHeavyBash', 'WoodHeavyBash', 'WoodLightBash', 'WoodMediumBash' */
    export let Attack2WeaponSound = new FieldUnitString("ucs2")
    /** 'normal', 'instant', 'artillery', 'aline', 'missile', 'splash', 'bounce', 'line' */
    export let Attack2WeaponType = new FieldUnitString("ua2w")
    export let DefaultActiveAbility = new FieldUnitString("udaa")
    export let DependencyEquivalents = new FieldUnitString("udep")
    export let Description = new FieldUnitString("ides")
    export let HitPointsRegenerationType = new FieldUnitString("uhrt")
    export let Hotkey = new FieldUnitString("uhot")
    export let IconGameInterface = new FieldUnitString("uico")
    export let IconScoreScreen = new FieldUnitString("ussi")
    export let ItemsSold = new FieldUnitString("usei")
    export let ModelFile = new FieldUnitString("umdl")
    export let ModelFileExtraVersions = new FieldUnitString("uver")
    export let MovementSound = new FieldUnitString("umsl")
    export let MovementType = new FieldUnitString("umvt")
    export let Name = new FieldUnitString("unam")
    export let NameEditorSuffix = new FieldUnitString("unsf")
    export let NormalAbilities = new FieldUnitString("uabi")
    export let Race = new FieldUnitString("urac")
    export let RandomSound = new FieldUnitString("ursl")
    export let RequiredAnimationNames = new FieldUnitString("uani")
    export let RequiredAnimationNamesAttachments = new FieldUnitString("uaap")
    export let RequiredAttachmentLinkNames = new FieldUnitString("ualp")
    export let RequiredBoneNames = new FieldUnitString("ubpr")
    export let Requirements = new FieldUnitString("ureq")
    export let RequirementsLevels = new FieldUnitString("urqa")
    export let ShadowImageUnit = new FieldUnitString("ushu")
    export let ShadowTextureBuilding = new FieldUnitString("ushb")
    export let TargetedAs = new FieldUnitString("utar")
    export let Tilesets = new FieldUnitString("util")
    export let TooltipBasic = new FieldUnitString("utip")
    export let TooltipExtended = new FieldUnitString("utub")
    export let UnitClassification = new FieldUnitString("utyp")
    export let UnitSoundSet = new FieldUnitString("usnd")
    export let UnitsSold = new FieldUnitString("useu")
    export let UpgradesUsed = new FieldUnitString("upgr")
    export let Hero_ConstructionSound = new FieldUnitString("ubsl")
    export let Hero_GroundTexture = new FieldUnitString("uubs")
    export let Hero_HeroAbilities = new FieldUnitString("uhab")
    export let Hero_HeroRevivalLocations = new FieldUnitString("urva")
    export let Hero_PrimaryAttribute = new FieldUnitString("upra")
    export let Hero_ProperNames = new FieldUnitString("upro")
    export let Hero_RequierementsForTier1 = new FieldUnitString("urq0")
    export let Hero_RequierementsForTier2 = new FieldUnitString("urq1")
    export let Hero_RequierementsForTier3 = new FieldUnitString("urq2")
    export let Hero_RequierementsForTier4 = new FieldUnitString("urq3")
    export let Hero_RequierementsForTier5 = new FieldUnitString("urq4")
    export let Hero_RequierementsForTier6 = new FieldUnitString("urq5")
    export let Hero_RequierementsForTier7 = new FieldUnitString("urq6")
    export let Hero_RequierementsForTier8 = new FieldUnitString("urq7")
    export let Hero_RequierementsForTier9 = new FieldUnitString("urq8")
    export let Hero_StructuresBuilt = new FieldUnitString("ubui")
    export let Hero_TooltipAwaken = new FieldUnitString("uawt")
    export let Hero_TooltipRevive = new FieldUnitString("utpr")
    export let ConstructionSound = new FieldUnitString("ubsl")
    export let GroundTexture = new FieldUnitString("uubs")
    export let ItemsMade = new FieldUnitString("umki")
    export let PathingMap = new FieldUnitString("upat")
    export let PlacementPreventedBy = new FieldUnitString("upar")
    export let PlacementRequires = new FieldUnitString("upap")
    export let ResearchesAvailable = new FieldUnitString("ures")
    export let UnitsTrained = new FieldUnitString("utra")
    export let UpgradesTo = new FieldUnitString("uupt")
}